version: "3.1"
services:

  nginx:
    image: tutum/nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/lara-todo.loc.conf
      - ./nginx/default:/etc/nginx/sites-enabled/lara-todo.loc.conf
      - /var/log/nginx/error.log:/var/log/nginx/error.log
      - /var/log/nginx/access.log:/var/log/nginx/access.log

  php-fpm:
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
      - ./public:/var/www/lara-todo.loc/public